version: '3'
services:
  server:
    build: ./server
    command: /bin/sh ./start.sh
    ports:
      - "3030:80"
    environment:
      - DEBUG=0
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=server.settings

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://api.timohus.com
    ports:
      - "9000:80"
    depends_on:
      - server

  web:
    image: nginx:latest
    volumes:
      - ./init-letsencrypt.sh:/init-letsencrypt.sh
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
      - server
    command: "/bin/sh -c 'chmod +x /init-letsencrypt.sh && /init-letsencrypt.sh && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"