version: '3'
services:
  server:
    build: ./server
    container_name: server
    expose:
      - 3030
    networks:
      - main
    environment:
      - DEBUG=0

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://api.timohus.com
    container_name: client
    expose:
      - 3000
    networks:
      - main

  web:
    image: nginx:1.19.6-alpine
    container_name: web-server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - main
    depends_on:
      - client
      - server

networks:
  main:
    driver: bridge