version: '3'
services:
  server:
    build: ./server
    container_name: server
    expose:
      - 3030
    networks:
      - main
    environment:
      - DEBUG=0

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://api.timohus.com
    container_name: client
    expose:
      - 3000
    networks:
      - main

  web:
    image: nginx:1.19.6-alpine
    container_name: web-server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - main
    depends_on:
      - client
      - server
      - certbot

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email timohus@gmail.com --agree-tos --no-eff-email -d timohus.com -d api.timohus.com -d bacterial-colony-classifier.timohus.com
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/certbot

networks:
  main:
    driver: bridge