version: '3'
services:
  server:
    build: ./server
    command: /bin/sh ./start.sh
    ports:
      - "3030:80"
    environment:
      - DEBUG=0
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=server.settings

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://api.timohus.com
    ports:
      - "9000:80"
    depends_on:
      - server

  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "80:80"
    - "443:443"
