version: '3'
services:
  rb-server:
    build: ./server
    volumes:
    - ./server:/code
    working_dir: /code
    command: python manage.py runserver 0.0.0.0:3000
    ports:
    - "3001:3000"
    environment:
    - DEBUG=1
    - PYTHONUNBUFFERED=1
    - DJANGO_SETTINGS_MODULE=server.settings

  rb-client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: base
      args:
        - REACT_APP_API_HOST=http://localhost:3001/
    volumes:
      - ./client:/code
    working_dir: /code
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - rb-server
