name: Deploy
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
#      - name: ls -a via ssh
#        uses: fifsky/ssh-action@master
#        with:
#          command: |
#            cd /tmp
#            ls -a
#          host: ${{ secrets.SSH_HOST }}
#          user: root
#          key: ${{ secrets.SSH_PRIVATE_KEY}}
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Test
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'git status'